
DATA LT_GLIEDERUNG TYPE TABLE OF ML_ESLL.
DATA LV_GLIEDERUNG TYPE ML_ESLL.

REFRESH GT_LEISTUNG.

CALL FUNCTION 'MS_SUBDIVISION_FOR_PRINT'
EXPORTING
PACKNO           = <FS>-PACKNO  "eslh-hpackno
ONLINE_DATA      = IV_FROM_MEM
TABLES
GLIEDERUNG       = LT_GLIEDERUNG
EXCEPTIONS
PACKNO_NOT_EXIST = 01.

LOOP AT LT_GLIEDERUNG INTO LV_GLIEDERUNG.
CALL FUNCTION 'MS_SERVICES_FOR_PRINT'
EXPORTING
PACKNO            = LV_GLIEDERUNG-SUB_PACKNO
ONLINE_DATA       = IV_FROM_MEM
TABLES
LEISTUNG          = GT_LEISTUNG
EXCEPTIONS
NO_SERVICES_FOUND = 01.
ENDLOOP.

*** INICIO MODIF. - 2483 - 12012026 - PTECHABAP01
IF <fs>-matnr IS INITIAL OR <FS>-PSTYP = '9'.
  APPEND LINES OF gt_leistung TO gt_serv_price.
ENDIF.
*** FIN MODIF.    - 2483 - 12012026 - PTECHABAP01














